# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0003_auto_20160618_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
