# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0004_auto_20160812_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='count',
        ),
    ]
