# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0005_remove_bookmark_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='hash_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
