# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0006_auto_20170422_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='hash_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
